benchmark:
  id: 1b
  version: 1
data:
- name: timestep
  values: 0.00195312
- name: free_energy
  transform:
  - as: free_energy
    expr: datum.energy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  values:
  - energy: 319.045
    time: 0
  - energy: 318.155
    time: 7.61719
  - energy: 315.555
    time: 15.2344
  - energy: 307.135
    time: 22.8516
  - energy: 283.973
    time: 30.4688
  - energy: 242.644
    time: 38.0859
  - energy: 214.109
    time: 45.7031
  - energy: 205.499
    time: 53.3203
  - energy: 200.944
    time: 60.9375
  - energy: 196.86
    time: 68.5547
  - energy: 192.77
    time: 76.1719
- name: run_time
  values:
  - sim_time: 192.77
    wall_time: 1142.51
- name: memory_usage
  values:
  - unit: KB
    value: 33844
metadata:
  author:
    email: trevor.keller@nist.gov
    first: Trevor
    github_id: tkphd
    last: Keller
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 2
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: mmsp
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/no-flux/
      version: 05a5db5111d92b916d51e143adf068547c3a654d
  summary: Parallel Travis CI benchmark with MMSP, no-flux domain
  timestamp: Tue, 10 Jan 2017 01:20:43 +0000
