benchmark:
  id: 1b
  version: 1
data:
- name: run_time
  values:
  - sim_time: 10000.0
    wall_time: 1089.121
- name: memory_usage
  values:
  - unit: MB
    value: 4.64
- format:
    parse:
      F: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: free_energy
    expr: datum.F
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/dschwen/75c5f5f47519119fdb6e934056f6fd56/raw/d865f3213e4a695dc031c37e71b280248c4a0eb5/problem_1b_out.csv
metadata:
  author:
    email: daniel.schwen@inl.gov
    first: Daniel
    github_id: dschwen
    last: Schwen
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 8
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/dschwen/CHiMaD_Hackathon
      version: cf1ab8d
  summary: Benchmark with MOOSE on macPro, no-flux domain
  timestamp: 1/24/2017
