benchmark:
  id: 1b
  version: 1
data:
- name: run_time
  values:
  - sim_time: 10000.0
    wall_time: 14262.998
- name: memory_usage
  values:
  - unit: MB
    value: 796
- format:
    parse:
      F: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: free_energy
    expr: datum.F
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/dschwen/e98885861ef77c480a74c13d09804f92/raw/a11dfd5d1d3856ec48b14fd321a7ccbfce45bd96/problem_1b_out.csv
metadata:
  author:
    email: daniel.schwen@inl.gov
    first: Daniel
    github_id: dschwen
    last: Schwen
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 4
    cpu_architecture: armv7l
    nodes: 1
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://github.com/dschwen/CHiMaD_Hackathon
      version: cf1ab8d
  summary: Raspberry Pi 3 benchmark with MOOSE, no-flux domain
  timestamp: 1/27/2017
