metadata:
  author:
    first: Trevor
    last: Keller
    email: trevor.keller@nist.gov
    github_id: tkphd
  simulation_name: hiperc_cuda
  summary: HiPerC spinodal decomposition result using CUDA on a Tesla P100 with 9-point discrete Laplacian
  timestamp: '18 December, 2017'
  implementation:
    repo:
      url: 'https://github.com/usnistgov/hiperc'
      version: b25b14acda7c5aef565cdbcfc88f2df3412dcc46
    name: custom
    container_url: ''
  hardware:
    cpu_architecture: x86_64
    acc_architecture: none
    parallel_model: threaded
    clock_rate: '1.48'
    cores: '1792'
    nodes: 1
benchmark:
  id: 1b
  version: '1'
data:
  - name: run_time
    values:
      - wall_time: '7388'
        sim_time: '200000'
  - name: memory_usage
    values:
      - unit: KB
        value: '308224'
  - name: free_energy
    type: line
    url: https://ndownloader.figshare.com/files/10030003
    format:
      parse:
        time: number
        free_energy: number
      type: csv
    description: free energy data
    transform:
      - as: y
        expr: datum.free_energy
        type: formula
      - as: x
        expr: datum.sim_time
        type: formula
  - name: image_000
    description: microstructure at t=0
    type: image
    url: https://ndownloader.figshare.com/files/10030006
  - name: image_005
    description: microstructure at t=5,000
    type: image
    url: https://ndownloader.figshare.com/files/10030009
  - name: image_010
    description: microstructure at t=10,000
    type: image
    url: https://ndownloader.figshare.com/files/10030012
  - name: image_020
    description: microstructure at t=20,000
    type: image
    url: https://ndownloader.figshare.com/files/10030015
  - name: image_050
    description: microstructure at t=50,000
    type: image
    url: https://ndownloader.figshare.com/files/10030018
  - name: image_100
    description: microstructure at t=100,000
    type: image
    url: https://ndownloader.figshare.com/files/10030021
  - name: image_120
    description: microstructure at t=120,000
    type: image
    url: https://ndownloader.figshare.com/files/10071574
  - name: image_150
    description: microstructure at t=150,000
    type: image
    url: https://ndownloader.figshare.com/files/10030024
  - name: image_200
    description: microstructure at t=200,000
    type: image
    url: https://ndownloader.figshare.com/files/10030027
