benchmark:
  id: 1c
  version: 1
data:
- name: free_energy
  transform:
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  values:
  - free_energy: 31.882942771008185
    time: 0.0
  - free_energy: 16.67296583996265
    time: 63.84021042362751
  - free_energy: 12.906737883664295
    time: 127.01883851836759
  - free_energy: 11.983601365109191
    time: 183.15341155666349
  - free_energy: 10.749546784544776
    time: 242.99355886373758
  - free_energy: 9.954740413521417
    time: 302.7582200539157
  - free_energy: 9.759375327718615
    time: 355.36246048066045
  - free_energy: 9.61554133790171
    time: 407.7923903446872
  - free_energy: 9.428639867543119
    time: 463.10144410049776
- name: run_time
  values:
  - sim_time: 463.10144410049776
    wall_time: 320.29
- name: memory_usage
  values:
  - unit: KB
    value: 306448
metadata:
  author:
    email: trevor.keller@nist.gov
    first: Trevor
    github_id: tkphd
    last: Keller
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 1
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: fipy
    repo:
      url: https://github.com/usnistgov/FiPy-spinodal-decomposition-benchmark/tree/master/T-shape/
      version: 944284638f00c3a411a71981d27becf97a2eb0e4
  summary: Serial Travis CI benchmark with FiPy, T-shape domain
  timestamp: Tue, 10 Jan 2017 01:27:20 +0000
