_id: 0dc3d1f0-76fd-11e7-a3e9-cb63094aa20f
benchmark:
  id: 6a
  version: '0'
data:
- description: Free Energy Plot
  format:
    parse:
      TotalEnergy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.TotalEnergy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://dl.dropbox.com/s/qusutz8g24hx54q/free_energy.csv
- name: run_time
  values:
  - sim_time: '400'
    wall_time: '1800'
- name: memory_usage
  values:
  - unit: KB
    value: '620000'
date: 1501621489
metadata:
  author:
    email: andrea.jokisaari@northwestern.edu
    first: A. M.
    github_id: amjokisaari
    last: Jokisaari
  hardware:
    acc_architecture: none
    clock_rate: '2.7'
    cores: '6'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: distributed
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://www.dropbox.com/s/qusutz8g24hx54q/free_energy.csv
      version: '00000'
  simulation_name: coral_6a
  summary: Upload-a-thon August 2017 test upload
  timestamp: 31 July, 2017
