_id: d0968fd0-76f6-11e7-a3e9-cb63094aa20f
benchmark:
  id: 6b
  version: '0'
data:
- description: Free Energy Plot
  format:
    parse:
      Energy: number
      Time: number
    type: csv
  name: free_energy
  transform:
  - as: y
    expr: datum.Energy
    type: formula
  - as: x
    expr: datum.Time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/f949e0b20e6195159e0bc79c9be3accc/raw/c6801b175376edebbd21fdfb5e01c8fed8683247/energy_6b.csv
- name: run_time
  values:
  - sim_time: '400'
    wall_time: '10140'
- name: memory_usage
  values:
  - unit: KB
    value: '1024000'
date: 1501618809
metadata:
  author:
    email: stvdwtt@umich.edu
    first: Stephen
    github_id: stvdwtt
    last: DeWitt
  hardware:
    acc_architecture: none
    clock_rate: '2.6'
    cores: '16'
    cpu_architecture: x86_64
    nodes: '1'
    parallel_model: distributed
  implementation:
    container_url: ''
    name: prisms
    repo:
      url: https://github.com/prisms-center/phaseField/tree/v2.0pre/applications/cahnHilliard_electrostatics_Curved
      version: 5005c86bb9106861f3cb134c0e7e1b115e15bb85
  simulation_name: prismspf_6b
  summary: Results data for problem 2b using PRISMS-PF v2.0pre and the Flux cluster
    at the University of Michigan
  timestamp: 28 July, 2017
