benchmark:
  id: 1c
  version: 1
data:
- name: timestep
  values: 0.00195312
- name: free_energy
  transform:
  - as: free_energy
    expr: datum.energy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  values:
  - energy: 31.8815
    time: 0
  - energy: 31.7653
    time: 7.61719
  - energy: 31.3578
    time: 15.2344
  - energy: 29.8382
    time: 22.8516
  - energy: 26.3998
    time: 30.4688
  - energy: 23.095
    time: 38.0859
  - energy: 21.4502
    time: 45.7031
  - energy: 20.4617
    time: 53.3203
  - energy: 19.8369
    time: 60.9375
  - energy: 19.3948
    time: 68.5547
  - energy: 19.0146
    time: 76.1719
- name: run_time
  values:
  - sim_time: 19.0146
    wall_time: 189.44
- name: memory_usage
  values:
  - unit: KB
    value: 32504
metadata:
  author:
    email: trevor.keller@nist.gov
    first: Trevor
    github_id: tkphd
    last: Keller
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 2
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: mmsp
    repo:
      url: https://github.com/mesoscale/MMSP-spinodal-decomposition-benchmark/tree/master/T-shape/
      version: 05a5db5111d92b916d51e143adf068547c3a654d
  summary: Parallel Travis CI benchmark with MMSP, T-shape domain
  timestamp: Tue, 10 Jan 2017 01:40:01 +0000
