benchmark:
  id: 2d
  version: 1
data:
- name: run_time
  values:
  - sim_time: 123808.02465468
    unit: s
    wall_time: 141240
- name: memory_usage
  values:
  - unit: GB
    value: 14.8
- format:
    parse:
      TotalEnergy: number
      time: number
    type: csv
  name: free_energy
  transform:
  - as: free_energy
    expr: datum.TotalEnergy
    type: formula
  - as: y
    expr: datum.free_energy
    type: formula
  - as: x
    expr: datum.time
    type: formula
  type: line
  url: https://gist.githubusercontent.com/wd15/41e21ea1090057c42a59380d90367763/raw/eba1e44ec25a2d9a906b2c802596778892b2f676/hackathon_p2_sphere_STA_v2_dfdt.csv
metadata:
  author:
    email: andrea.jokisaari@northwestern.edu
    first: A. M.
    github_id: amjokisaari
    last: Jokisaari
  hardware:
    acc_architecture: none
    clock_rate: 0
    cores: 40
    cpu_architecture: x86_64
    nodes: 1
  implementation:
    container_url: ''
    name: moose
    repo:
      url: https://bitbucket.org/ajokisaari/coral
      version: e8fc74f
  summary: Metadata for the Benchmark2 problems
  timestamp: 6/28/2016
